version: '3'

services:
  db:
    image: mariadb:10.4
    container_name: mariadb
    networks: 
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: magento
      MARIADB_USER: magento
      MARIADB_PASSWORD: magento
  elastic:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    networks: 
      - backend
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
  web:
    image: ataberkylmz/magento2:2.4.2
    container_name: magento2-container
    networks:
      backend:
        aliases:
          - magento2.test.com
    environment:
      - DB_SERVER=mariadb
      - ELASTICSEARCH_SERVER=elasticsearch
      - MAGENTO_HOST=magento2.test.com
      - VIRTUAL_HOST=magento2.test.com
      - ADMIN_URLEXT=admin
      - ADMIN_USERNAME
      - ADMIN_PASSWORD

    depends_on:
      - db
      - elastic
    volumes:
      - ../:/data/extensions/workdir
      - ./scripts/mftf.sh:/var/www/html/mftf.sh

  ## Selenium for MFTF tests
  selenium:
   image: selenium/standalone-chrome-debug:3.8.1
   ports:
     - "5900:5900"
   networks: 
    - backend
networks:
  backend:
