language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

install:
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
    - composer install --prefer-dist

script:
    - php vendor/bin/phpcs
    - vendor/bin/phpunit -c Test/phpunit.xml