blank_issues_enabled: false
contact_links:
  - name: Adyen Support
    url: https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420
    about: For other questions, contact our support team
